services:
  redis:
    image: redis:7.4
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - chat-app-network

  chat-app:
    build: .
    container_name: chat-app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "80:80"
    networks:
      - chat-app-network
    depends_on:
      - redis
  
networks:
  chat-app-network:
    driver: bridge
    